spring.application.name=vanderler-backend
server.port=8080

#MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/vanderlerdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#JWT
vanderler.jwt.secret=9f8as7df-asdf98as7df-asd8f76asdf-098as7df098as7df-asd980as7df
vanderler.jwt.expiration=86400000
